//============================================================================
//  Falcon: Hatari's 68020/030 prefetch pipeline model (docs/CPU_TIMING.md)
//
//  Hatari's cycle-exact 68030 stops prefetching ahead of an unconditional
//  flow change (RTS, RTE, RTD, RTR, JSR, JMP, BSR): pipeline_020()
//  (cpu/newcpu.c:9503-9586, MORE_ACCURATE_68020_PIPELINE) scans the
//  instruction stream one word per word consumed, two words ahead of the
//  consumption (the queue's prefetch020[1]), decoding instruction lengths
//  from its opcode table (cpudatatbl: length, disp020, branch); when it
//  decodes such a branch it stops further fetches "one word early", until
//  the branch refills the queue (fill_prefetch_030_ntx, reset_pipeline_state).
//
//  This module runs the same scanner over the AP68030's prefetch queue
//  (ap030_top tm_q/tm_qn/tm_scan/tm_flush), one word per processor clock (on
//  its clock enable, so the processor's behaviour stays a function of its
//  own clocks) as the words arrive, with Hatari's table in block RAM (falcon_optbl.mem, generated by
//  tools/optbl from Hatari's own tables).  When the stop becomes active at
//  the scan of the word at A, the fetch decisions at consumptions from A-4
//  on are blocked: stop_at = A, and the AP68030 (fetch_lazy) fetches no
//  longword once the next word to take is at stop_at - 2 or beyond.  Hatari
//  decides each fetch after scanning the word two ahead of the consumption;
//  the AP68030's words arrive later than Hatari's (instantly fetched) ones,
//  so while scanning it waits until scan_to has passed that word (or the
//  words below the longword it wants).
//
//  As in Hatari, a refill to T scans from T on (add_prefetch_030 scans each
//  word it adds), an instruction's length excludes its brief/full extension
//  words, which the step where pipeline_pos == disp020 consumes (adding the
//  base/outer displacement of a full format), and an F-line opcode
//  (variable length) ends the scan until the next refill.  The processor can
//  take two or three words in a clock, before the scan reaches them (an
//  opcode and its extension words, right after they arrive), so the scanner
//  keeps the next two words to scan as it sees them in the queue and scans
//  them from there (the scan was never more than one word behind the queue
//  in the benches: tb/bustime, tb/system "scan lag"); a word that left the
//  queue unseen ends the scan until the next refill.
//============================================================================

module falcon_pipescan #(parameter OPTBL_MEM = "rtl/falcon/falcon_optbl.mem")
(
	input             clk,
	input             ce,          // the processor's clock enable: the scan runs on its clocks
	input             enable,      // the processor uses fetch_lazy (Falcon mode)
	input      [95:0] q,           // prefetch queue, word 0 (at scan) in [95:80]
	input       [2:0] qn,          // words in it
	input      [31:0] scan,        // address of word 0
	input             flush,       // the queue was flushed or reloaded last clock
	output reg        stop_v,
	output reg [31:0] stop_at,
	output            scan_v,      // scanning: fetch decisions wait for scan_to
	output     [31:0] scan_to      // the first word not yet scanned
);

// Hatari's opcode table: [2:0] length in words (7: variable), [3] stop,
// [6:4] disp020[0] / 2, [8:7] disp020[1] / 2
reg [8:0] optbl [0:65535];
initial $readmemb(OPTBL_MEM, optbl);
reg [8:0] rd;                  // the entry of the word taken last clock

reg [31:0] sa;                 // the next word to scan
reg [15:0] sh0, sh1;           // the words at sa, sa+2 ...
reg  [1:0] shv;                // ... when seen in the queue
reg        act;                // scanning
reg        pend;               // a word was taken last clock: its step now
reg [15:0] w;                  // that word
reg [31:0] wa;                 // its address
reg  [4:0] pos;                // pipeline_pos (bytes)
reg  [2:0] r8a, r8b;           // pipeline_r8[0], [1] (bytes)
reg  [1:0] stp;                // pipeline_stop: 0, 1, 2 (= -1)
assign scan_v  = act;
assign scan_to = pend ? wa : sa;

// the words at sa + 2j (j = 0..2): from the shadow, or from the queue
wire [31:0] off   = sa - scan;
wire        near  = (off[31:5] == 27'd0) || (off[31:5] == {27{1'b1}});   // -32 <= off < 32
wire  [4:0] oi    = off[5:1];  // then sa's word index in the queue (signed)
wire  [2:0] inq;
wire [15:0] qw0, qw1, qw2;
function [16:0] qword;         // {in the queue, the word} for word index i (signed)
	input [4:0] i;
	qword = {near && !i[4] && (i[3:0] < {1'b0, qn}), q[95 - 16 * i[2:0] -: 16]};
endfunction
assign {inq[0], qw0} = qword(oi);
assign {inq[1], qw1} = qword(oi + 5'd1);
assign {inq[2], qw2} = qword(oi + 5'd2);
wire  [1:0] av  = shv | inq[1:0];                 // available
wire [15:0] aw0 = shv[0] ? sh0 : qw0;
wire [15:0] aw1 = shv[1] ? sh1 : qw1;
wire        gone  = !av[0] && off[31];   // the processor consumed it unseen
/* verilator lint_off UNUSEDSIGNAL */
wire        unused_ps = off[0] | (|w[15:9]) | (|w[7:6]) | (|w[3:2]);   // (sa is even; only these bits of w matter)
/* verilator lint_on UNUSEDSIGNAL */

// one scanner step for the word w (Hatari's pipeline_020 body)
reg  [4:0] n_pos;
reg  [2:0] n_r8a, n_r8b;
reg  [1:0] n_stp;
reg        n_lost, n_stopnow;
reg  [4:0] extra;
always @* begin
	n_pos = pos; n_r8a = r8a; n_r8b = r8b; n_stp = stp; n_lost = 1'b0; n_stopnow = 1'b0;
	extra = ((w[5:4] == 2'b10) ? 5'd2 : (w[5:4] == 2'b11) ? 5'd4 : 5'd0) +
	        ((w[1:0] == 2'b10) ? 5'd2 : (w[1:0] == 2'b11) ? 5'd4 : 5'd0);
	if (pos != 5'd0 && pos == {2'b00, r8a}) begin
		n_r8a = 3'd0;
		if (w[8]) n_pos = pos + extra;
	end
	else if (pos != 5'd0 && pos == {2'b00, r8b}) begin
		n_r8b = 3'd0;
		if (w[8]) n_pos = pos + extra;
	end
	else if (pos > 5'd2) begin
		n_pos = pos - 5'd2;
		if (stp == 2'd1 && pos - 5'd2 == 5'd2) begin n_stp = 2'd2; n_stopnow = 1'b1; end
	end
	else if (stp != 2'd0) begin
		if (stp == 2'd1) n_stopnow = 1'b1;
		n_stp = 2'd2;
	end
	else if (rd[2:0] == 3'd7) n_lost = 1'b1;          // variable length: no more scanning
	else begin                                          // a new instruction
		n_pos = {1'b0, rd[2:0], 1'b0};
		n_r8a = {rd[5:4], 1'b0};
		n_r8b = {rd[8:7], 1'b0};
		if (rd[6]) n_r8a = 3'd0;                        // (positions above 6 do not occur)
		if (rd[2:0] != 3'd0 && rd[3]) n_stp = 2'd1;
	end
end

always @(posedge clk) if (ce) begin
	rd <= optbl[aw0];
	if (flush || !enable) begin
		sa <= scan; act <= enable; pend <= 1'b0; shv <= 2'd0;
		pos <= 5'd0; r8a <= 3'd0; r8b <= 3'd0; stp <= 2'd0;
		stop_v <= 1'b0;
	end else if (act) begin
		if (pend) begin
			pos <= n_pos; r8a <= n_r8a; r8b <= n_r8b; stp <= n_stp;
			if (n_stopnow) begin stop_v <= 1'b1; stop_at <= wa; end
			if (n_lost || n_stopnow) act <= 1'b0;   // nothing more to decide
		end
		pend <= 1'b0;
		{sh0, sh1} <= {aw0, aw1};
		shv <= av;
		if (gone) act <= 1'b0;
		else if (av[0] && !(pend && (n_lost || n_stopnow))) begin
			w <= aw0; wa <= sa; pend <= 1'b1; sa <= sa + 32'd2;
			{sh0, sh1} <= {aw1, qw2};
			shv <= {inq[2], av[1]};
		end
	end
end

endmodule
